app_announce:
    resource: "@AppBundle/Controller/Front/AnnounceController.php"
    type:     annotation

back:
    resource: '@AppBundle/Controller/Back'
    type: annotation
    prefix: /admin/

front:
    resource: '@AppBundle/Controller/Front'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"